# https://aka.ms/yaml

resources:
- repo: self
queue:
  name: Hosted VS2017
steps:
- powershell: |
   .\go.ps1 -msbuild "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\msbuild.exe" -packageSources $(DXApiFeed)
  displayName: 'Build'
  failOnStderr: true
- task: VSTest@2
  displayName: 'VsTest - testAssemblies'
  inputs:
    testAssemblyVer2: |
     .\bin\DevExpress.XAF.Agnostic.Specifications.dll
    uiTests: true

